services:
  craigdb:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: craig
      POSTGRES_DB: craig
      POSTGRES_USER: craig
    ports:
      - "5423:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U craig"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - 'db_data:/var/lib/postgresql/data'
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  craig:
    build:
      context: .
      args:
        - NODE_VERSION=${NODE_VERSION:-20.11.0}
    environment:
      - NODE_VERSION=${NODE_VERSION:-20.11.0}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_APP_ID=${DISCORD_APP_ID}
      - API_HOMEPAGE=${API_HOMEPAGE}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIS_START_TIMEOUT_S=${REDIS_START_TIMEOUT_S:-30}
      - POSTGRESQL_START_TIMEOUT_S=${POSTGRESQL_START_TIMEOUT_S:-30}
      - REDIS_HOST=${REDIS_HOST:-redis}
    ports:
      - "7777:3000"
      - "5029:5029"
    depends_on:
      craigdb:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
    volumes:
      - 'craig_rec:/app/rec'

volumes:
  db_data:

  craig_rec:




