services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: craig
      POSTGRES_DB: craig
      POSTGRES_USER: craig
    ports:
      - "5423:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U craig"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - 'db_data:/var/lib/postgresql/data'
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  craig:
    build:
      context: .
      args:
        # This tells Compose to grab the Dokploy variables and pass them to the build
        - NODE_VERSION=${NODE_VERSION}
        - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
        - DISCORD_APP_ID=${DISCORD_APP_ID}
        - API_HOMEPAGE=${API_HOMEPAGE}
        - DATABASE_NAME=${DATABASE_NAME}
        - POSTGRESQL_USER=${POSTGRESQL_USER}
        - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
        # You can also set default fallbacks here just in case
        - REDIS_START_TIMEOUT_S=${REDIS_START_TIMEOUT_S:-30}
        - POSTGRESQL_START_TIMEOUT_S=${POSTGRESQL_START_TIMEOUT_S:-30}
    ports:
      - "7777:3000"
      - "5029:5029"
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
    volumes:
      - 'craig_rec:/app/rec'

volumes:
  db_data:

  craig_rec:



